#!/usr/bin/env python3
"""Build the deterministic remote-code Marlin source bundle."""
from __future__ import annotations

import base64
import hashlib
import io
import textwrap
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "rwkv7_hf" / "csrc" / "marlin"
OUTPUT = ROOT / "rwkv7_hf" / "native_quant_marlin_sources.py"


def build_payload() -> tuple[bytes, list[str]]:
    files = sorted(path for path in SOURCE.rglob("*") if path.is_file())
    buffer = io.BytesIO()
    with zipfile.ZipFile(
        buffer,
        "w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=9,
    ) as archive:
        for path in files:
            relative = path.relative_to(SOURCE).as_posix()
            info = zipfile.ZipInfo(relative, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(
                info,
                path.read_bytes(),
                compress_type=zipfile.ZIP_DEFLATED,
                compresslevel=9,
            )
    return buffer.getvalue(), [path.relative_to(SOURCE).as_posix() for path in files]


def render() -> str:
    payload, files = build_payload()
    digest = hashlib.sha256(payload).hexdigest()
    encoded = base64.b85encode(payload).decode("ascii")
    chunks = "\n".join(f'    "{part}"' for part in textwrap.wrap(encoded, 100))
    file_lines = "\n".join(f'    "{name}",' for name in files)
    return f'''# coding=utf-8
# SPDX-License-Identifier: Apache-2.0
"""Deterministic Marlin source bundle for Transformers remote-code caches.

Generated by ``scripts/build_marlin_source_bundle.py``. Do not edit manually.
The embedded files retain their original copyright/SPDX headers and LICENSE.
"""
from __future__ import annotations

import base64
import hashlib
import io
import os
import shutil
import tempfile
import zipfile
from pathlib import Path

_BUNDLE_SHA256 = "{digest}"
_BUNDLE_FILES = (
{file_lines}
)
_BUNDLE_B85 = (
{chunks}
)


def materialize_marlin_sources() -> Path:
    """Extract and return a stable cached source directory."""

    payload = base64.b85decode(_BUNDLE_B85.encode("ascii"))
    if hashlib.sha256(payload).hexdigest() != _BUNDLE_SHA256:
        raise RuntimeError("RWKV7 Marlin source bundle checksum mismatch")
    cache_base = Path(
        os.environ.get(
            "RWKV7_MARLIN_SOURCE_CACHE",
            Path.home() / ".cache" / "rwkv7_hf" / "marlin_sources",
        )
    ).expanduser()
    target = cache_base / _BUNDLE_SHA256[:16]
    marker = target / ".complete"
    if marker.is_file() and all((target / name).is_file() for name in _BUNDLE_FILES):
        return target

    cache_base.mkdir(parents=True, exist_ok=True)
    if target.exists() and not marker.is_file():
        shutil.rmtree(target, ignore_errors=True)
    temporary = Path(tempfile.mkdtemp(prefix="marlin-", dir=cache_base))
    try:
        with zipfile.ZipFile(io.BytesIO(payload)) as archive:
            archive.extractall(temporary)
        (temporary / ".complete").write_text(_BUNDLE_SHA256 + "\\n", encoding="utf-8")
        try:
            temporary.replace(target)
        except OSError:
            if not marker.is_file():
                raise
    finally:
        if temporary.exists():
            shutil.rmtree(temporary, ignore_errors=True)
    if not all((target / name).is_file() for name in _BUNDLE_FILES):
        raise RuntimeError("RWKV7 Marlin source bundle extraction is incomplete")
    return target


__all__ = ["materialize_marlin_sources"]
'''


def main() -> int:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
